### ISSUE TITLE
http error 500

### ISSUE THREAD

**Issue by kangyoedi** [ibnux/phpmixbill#5]
install di raspberry pi (raspbian / arch linux) setelah install muncul error http error 500??

**Comment by kangyoedi** [comment]
[Thu Nov 23 20:50:07.734748 2017] [:error] [pid 21768] [client 192.168.1.1:46316] PHP Fatal error:  Uncaught exception 'SmartyException' with message 'unable to write f
ile ui/compiled/wrt5a16d20fb2e907.72208893' in /var/www/html/phpmixbill/system/vendors/smarty/libs/sysplugins/smarty_internal_write_file.php:44\nStack trace:\n#0 /var/w
ww/html/phpmixbill/system/vendors/smarty/libs/sysplugins/smarty_internal_template.php(201): Smarty_Internal_Write_File::writeFile('ui/compiled/f0d...', '<?php /* Smarty
...', Object(Smarty))\n#1 /var/www/html/phpmixbill/system/vendors/smarty/libs/sysplugins/smarty_internal_templatebase.php(155): Smarty_Internal_Template->compileTemplat
eSource()\n#2 /var/www/html/phpmixbill/system/vendors/smarty/libs/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('admin.tpl', NUL
L, NULL, NULL, true)\n#3 /var/www/html/phpmixbill/system/controllers/admin.php(51): Smarty_Internal_TemplateBase->display('admin.tpl')\n#4 /var/www/html/phpmixbill/syst
em/boot.php(207): include('/var/www/html/p...')\n#5 /var/www/html/phpmixbill/index.php(13): require('/var/www/html/p...')\n# in /var/www/html/phpmixbill/system/vendors/
smarty/libs/sysplugins/smarty_internal_write_file.php on line 44

**Comment by kangyoedi** [comment]
change permission ui folder 777 

case solved
